# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InfinitePageViewController' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InfinitePageViewController

  pod 'THFlexiblePageController', :path => './'
  target 'InfinitePageViewControllerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InfinitePageViewControllerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'THFlexiblePageController' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for THFlexiblePageController

  target 'THFlexiblePageControllerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
